-- 速度榜改为按请求吞吐（tok/s）的中位数（docs/基准测试与排行榜数据服务技术方案.md §3.4：
-- "输出 tok/s 的 P50"）。00027 只存了输出 token 与生成耗时的总和，只能算加权平均；这里给
-- usage_hourly 与 public_model_usage_daily 加一组固定分桶的吞吐直方图，P50 在桶内线性插值。
-- 桶上界（tok/s）：10,20,30,40,50,60,80,100,125,150,200,300,500,+inf，
-- 与 internal/reqlog.SpeedBucketBounds 一一对应，改动需要同步迁移。
-- 只统计成功、流式、gen_ms > 0 的请求（与 speed_requests 同一口径）；历史行为 0。

-- +goose Up
-- +goose StatementBegin
ALTER TABLE usage_hourly ADD COLUMN spd_b0 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b1 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b2 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b3 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b4 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b5 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b6 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b7 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b8 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b9 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b10 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b11 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b12 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b13 BIGINT NOT NULL DEFAULT 0;
ALTER TABLE public_model_usage_daily ADD COLUMN spd_b0 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b1 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b2 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b3 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b4 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b5 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b6 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b7 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b8 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b9 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b10 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b11 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b12 BIGINT NOT NULL DEFAULT 0, ADD COLUMN spd_b13 BIGINT NOT NULL DEFAULT 0;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE public_model_usage_daily DROP COLUMN IF EXISTS spd_b0, DROP COLUMN IF EXISTS spd_b1, DROP COLUMN IF EXISTS spd_b2, DROP COLUMN IF EXISTS spd_b3, DROP COLUMN IF EXISTS spd_b4, DROP COLUMN IF EXISTS spd_b5, DROP COLUMN IF EXISTS spd_b6, DROP COLUMN IF EXISTS spd_b7, DROP COLUMN IF EXISTS spd_b8, DROP COLUMN IF EXISTS spd_b9, DROP COLUMN IF EXISTS spd_b10, DROP COLUMN IF EXISTS spd_b11, DROP COLUMN IF EXISTS spd_b12, DROP COLUMN IF EXISTS spd_b13;
ALTER TABLE usage_hourly DROP COLUMN IF EXISTS spd_b0, DROP COLUMN IF EXISTS spd_b1, DROP COLUMN IF EXISTS spd_b2, DROP COLUMN IF EXISTS spd_b3, DROP COLUMN IF EXISTS spd_b4, DROP COLUMN IF EXISTS spd_b5, DROP COLUMN IF EXISTS spd_b6, DROP COLUMN IF EXISTS spd_b7, DROP COLUMN IF EXISTS spd_b8, DROP COLUMN IF EXISTS spd_b9, DROP COLUMN IF EXISTS spd_b10, DROP COLUMN IF EXISTS spd_b11, DROP COLUMN IF EXISTS spd_b12, DROP COLUMN IF EXISTS spd_b13;
-- +goose StatementEnd
